In [2]:
import pandas as pd

In [4]:
df = pd.read_excel("Flipkart Sales Dataset.xlsx")
df.head()

,OrderDate,OrderID,Delivery Date,CustomerID,Customer Age,Customer Gender,Location,Zone,Delivery Type,Product Category,SubCategory,Product,Unit Price,Shipping Fee,Order Quantity,Sale Price,Status,Reason,Rating
0,2020-05-31,5136486,2020-06-04,230569424,57,M,Western,Zone 3,Express,Fashion,Girl's fashion,Fashion Girl's Dress Kids Children Newborn Bab...,147,10,2,196,Returned,Onsite -Description mismatch,2
1,2020-05-31,5136457,2020-06-12,230568182,24,F,Western,Zone 3,Standard Delivery,Health and beauty,Medical supplies and Equipment,Blood Pressure Monitor Digital Wrist BP Pulse ...,131,4,7,183,Returned,Product - Not fitting expectation,2
2,2020-05-31,5136465,2020-06-10,230567584,31,M,Weija,Zone 2,Standard Delivery,Health and beauty,Medical supplies and Equipment,Portable Blood Pressure Monitor - White,69,6,10,205,Delivered,NaN,3
3,2020-05-31,5136488,2020-06-05,230563788,62,F,Greater Accra,Zone 1,Express,Phones and Tablet,Mobile phones,Samsung A3 Core Dual SIM - 16GB HDD - 1GB RAM ...,148,7,7,291,Delivered,NaN,1
4,2020-05-31,5136449,2020-06-10,230563726,18,F,Weija,Zone 2,Shipped from Abroad,Fashion,Boy's fashion,Boys Sneakers Casual Kids Sports Shoes-Gold,126,12,9,260,Delivered,NaN,3

In [5]:
df.tail()

,OrderDate,OrderID,Delivery Date,CustomerID,Customer Age,Customer Gender,Location,Zone,Delivery Type,Product Category,SubCategory,Product,Unit Price,Shipping Fee,Order Quantity,Sale Price,Status,Reason,Rating
133498,2020-04-04,5115960,2020-04-18,230560355,24,F,Greater Accra,Zone 1,Standard Delivery,Phones and Tablet,Mobile phones,Infinix Smart HD X612 (2021) - 32GB HDD - 2GB ...,70,19,2,239,Delivered,NaN,5
133499,2020-04-04,5115962,2020-04-18,230557477,27,F,Greater Accra,Zone 1,Shipped from Abroad,Home and Office,Home and Furniture,Lindy 12 Cubes Wardrobe 8 Doors - Brown,94,14,5,268,Delivered,NaN,3
133500,2020-04-04,5115979,2020-04-16,230548894,37,M,Greater Accra,Zone 1,Standard Delivery,Electronics,Digital Cameras,Canon EOS 600D 18MP CMOS DSLR Camera - Black,81,18,1,237,Delivered,NaN,3
133501,2020-04-04,5115981,2020-04-22,230547230,38,F,Ashanti,Zone 3,Shipped from Abroad,Home and Office,Kitchen and dinning,Plastic Storage Bowl - 17 Pieces Green,146,16,10,260,Delivered,NaN,5
133502,2020-04-04,5115990,2020-04-07,230546677,45,M,Greater Accra,Zone 1,Express,Phones and Tablet,Mobile phones,Samsung A3 Core Dual SIM - 16GB HDD - 1GB RAM ...,60,15,3,203,Delivered,NaN,2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133503 entries, 0 to 133502
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   OrderDate         133503 non-null  datetime64[ns]
 1   OrderID           133503 non-null  int64
 2   Delivery Date     133503 non-null  datetime64[ns]
 3   CustomerID        133503 non-null  int64
 4   Customer Age      133503 non-null  int64
 5   Customer Gender   133503 non-null  object
 6   Location          133503 non-null  object
 7   Zone              133503 non-null  object
 8   Delivery Type     133503 non-null  object
 9   Product Category  133503 non-null  object
 10  SubCategory       133503 non-null  object
 11  Product           133503 non-null  object
 12  Unit Price        133503 non-null  int64
 13  Shipping Fee      133503 non-null  int64
 14  Order Quantity    133503 non-null  int64
 15  Sale Price        133503 non-null  int64
 16  Status            133503 non-null  object
 17  Reason            34981 non-null   object
 18  Rating            133503 non-null  int64
dtypes: datetime64[ns](2), int64(8), object(9)
memory usage: 19.4+ MB

In [7]:
df.isnull().sum()

OrderDate               0
OrderID                 0
Delivery Date           0
CustomerID              0
Customer Age            0
Customer Gender         0
Location                0
Zone                    0
Delivery Type           0
Product Category        0
SubCategory             0
Product                 0
Unit Price              0
Shipping Fee            0
Order Quantity          0
Sale Price              0
Status                  0
Reason              98522
Rating                  0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(20502)

In [12]:
df = df.drop_duplicates()

In [13]:
df.shape

(113001, 19)

In [14]:
df.describe()

,OrderDate,OrderID,Delivery Date,CustomerID,Customer Age,Unit Price,Shipping Fee,Order Quantity,Sale Price,Rating
count,113001,1.130010e+05,113001,1.130010e+05,113001.000000,113001.00000,113001.000000,113001.000000,113001.000000,113001.000000
mean,2018-02-22 15:57:18.670454272,5.079973e+06,2018-03-04 04:35:42.012902400,2.305156e+08,35.919700,99.95300,11.500500,5.334776,224.967089,2.729923
min,2015-01-01 00:00:00,5.023455e+06,2015-01-03 00:00:00,2.304591e+08,17.000000,50.00000,3.000000,1.000000,150.000000,1.000000
25%,2016-08-10 00:00:00,5.051716e+06,2016-08-19 00:00:00,2.304874e+08,28.000000,75.00000,7.000000,3.000000,187.000000,2.000000
50%,2018-03-18 00:00:00,5.079970e+06,2018-03-27 00:00:00,2.305156e+08,35.000000,100.00000,12.000000,5.000000,225.000000,3.000000
75%,2019-10-28 00:00:00,5.108234e+06,2019-11-06 00:00:00,2.305439e+08,43.000000,125.00000,16.000000,8.000000,263.000000,4.000000
max,2020-12-31 00:00:00,5.136490e+06,2021-01-20 00:00:00,2.305721e+08,87.000000,150.00000,20.000000,10.000000,300.000000,5.000000
std,NaN,3.263158e+04,NaN,3.261603e+04,11.021838,29.19532,5.192101,2.924385,43.567197,1.355430

In [15]:
df.columns

Index(['OrderDate', 'OrderID', 'Delivery Date', 'CustomerID', 'Customer Age',
       'Customer Gender', 'Location', 'Zone', 'Delivery Type',
       'Product Category', 'SubCategory', 'Product', 'Unit Price',
       'Shipping Fee', 'Order Quantity', 'Sale Price', 'Status', 'Reason',
       'Rating'],
      dtype='object')

In [18]:
df["OrderID"].value_counts()

OrderID
5116087    2
5023480    1
5023497    1
5136463    1
5023503    1
          ..
5023459    1
5023469    1
5023481    1
5023495    1
5136462    1
Name: count, Length: 113000, dtype: int64

In [19]:
df["Customer Gender"].value_counts()

Customer Gender
M    58288
F    54713
Name: count, dtype: int64

In [20]:
df["Product Category"].value_counts()

Product Category
Health and beauty    35953
Fashion              33388
Phones and Tablet    17978
Home and Office      15408
Electronics          10274
Name: count, dtype: int64

In [21]:
df["SubCategory"].value_counts()

SubCategory
Vitamins & Dietary Supplements    12838
Men's fashion                     10273
Medical supplies and Equipment    10270
Boy's fashion                      7707
Beauty and personal care           7707
Women's fashion                    7705
Mobile phones                      7703
Girl's fashion                     7703
Kitchen and dinning                7703
Digital Cameras                    5138
Fragrances                         5138
Tablets                            5138
Mobile accessories                 5137
Home and Furniture                 5137
Home Audio                         5136
Tools and Home Improvement         2568
Name: count, dtype: int64

In [22]:
text_columns = [
    "Product Category",
    "SubCategory",
    "Product",
    "Customer Gender",
    "Location",
    "Zone",
    "Delivery Type",
    "Status",
    "Reason"
]

for col in text_columns:
    df[col] = df[col].str.strip()

In [23]:
df.dtypes

OrderDate           datetime64[ns]
OrderID                      int64
Delivery Date       datetime64[ns]
CustomerID                   int64
Customer Age                 int64
Customer Gender             object
Location                    object
Zone                        object
Delivery Type               object
Product Category            object
SubCategory                 object
Product                     object
Unit Price                   int64
Shipping Fee                 int64
Order Quantity               int64
Sale Price                   int64
Status                      object
Reason                      object
Rating                       int64
dtype: object

In [24]:
df[["Customer Age", "Order Quantity", "Unit Price", 
    "Sale Price", "Shipping Fee", "Rating"]].describe()

,Customer Age,Order Quantity,Unit Price,Sale Price,Shipping Fee,Rating
count,113001.000000,113001.000000,113001.00000,113001.000000,113001.000000,113001.000000
mean,35.919700,5.334776,99.95300,224.967089,11.500500,2.729923
std,11.021838,2.924385,29.19532,43.567197,5.192101,1.355430
min,17.000000,1.000000,50.00000,150.000000,3.000000,1.000000
25%,28.000000,3.000000,75.00000,187.000000,7.000000,2.000000
50%,35.000000,5.000000,100.00000,225.000000,12.000000,3.000000
75%,43.000000,8.000000,125.00000,263.000000,16.000000,4.000000
max,87.000000,10.000000,150.00000,300.000000,20.000000,5.000000

In [26]:
df["Delivery Days"] = (
    df["Delivery Date"] - df["OrderDate"]
).dt.days

In [27]:
df.columns

Index(['OrderDate', 'OrderID', 'Delivery Date', 'CustomerID', 'Customer Age',
       'Customer Gender', 'Location', 'Zone', 'Delivery Type',
       'Product Category', 'SubCategory', 'Product', 'Unit Price',
       'Shipping Fee', 'Order Quantity', 'Sale Price', 'Status', 'Reason',
       'Rating', 'Delivery Days'],
      dtype='object')

In [28]:
df.to_csv(
    "flipkart_sales_cleaned.csv",
    index=False
)